#36 Refactor: migrate to cyberway
GolosChain/golos-notifications pull request #38
Opened 2019-02-28 10:45 UTC by IvanBlacky

2019-02-28 10:46 UTC, bacher requested changes

2019-02-28 10:46 UTC, Bacher commented on docker-compose.yml
> +    notify-mongo:
Отступы не по формату, должно быть 2. Prettier

2019-02-28 10:47 UTC, bacher requested changes

2019-02-28 10:47 UTC, Bacher commented on src/controllers/registrator/Abstract.js
> +            return a;
Зачем в две строки?

2019-02-28 10:50 UTC, bacher requested changes

2019-02-28 10:50 UTC, Bacher commented on src/services/Registrator.js
> +            ...data.args,
Точно ...data.args должен быть в конце объекта?
Если в data.args останутся поля которые уже выше были объявлены, то они перезатрутся полями из data.args, такое поведение точно подразумевается?

2019-02-28 10:50 UTC, Bacher commented on src/services/Registrator.js
> +            // console.log(data);
console.log ?

2019-02-28 10:50 UTC, bacher requested changes

2019-02-28 10:50 UTC, Bacher commented on package.json
> +        "printWidth": 100,
Должно быть 2 пробела отступ

2019-02-28 10:51 UTC, IvanBlacky commented on src/services/Registrator.js
> +            ...data.args,
Да, такое поведение задумано

2019-02-28 10:51 UTC, bacher requested changes

2019-02-28 10:51 UTC, Bacher commented on src/controllers/registrator/Transfer.js
> +        console.log(quantity);
console.log

2019-02-28 10:51 UTC, Bacher commented on src/controllers/registrator/Transfer.js
> +        console.log(amount, quantity.sym);
console.log

2019-02-28 10:55 UTC, bacher requested changes

2019-02-28 10:55 UTC, Bacher commented on src/controllers/registrator/Abstract.js
> +        } catch (e) {
e переименовать

2019-02-28 10:55 UTC, Bacher commented on src/controllers/registrator/Abstract.js
> +        } catch (e) {
e переименовать

2019-02-28 10:57 UTC, bacher approved these changes

2019-02-28 11:08 UTC, Format-X22 requested changes

2019-02-28 11:08 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +            Logger.error(error);
А какого рода тут вообще могут появляться ошибки? Излишняя обертка.

2019-02-28 11:08 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +            Logger.error(error);
А какого рода тут вообще могут появляться ошибки? Излишняя обертка.

2019-02-28 11:08 UTC, Format-X22 commented on src/controllers/registrator/Transfer.js
> +        const amount = (1 / Math.pow(10, quantity.decs)) * quantity.amount;
core.type.BigNum

2019-02-28 11:08 UTC, Format-X22 commented on src/services/Registrator.js
> +        subscribe.on('block', data => {
Лучше подписываться до старта.

2019-02-28 11:08 UTC, Format-X22 commented on src/services/Registrator.js
> +            if (!transaction) {
С ядра 3.7 не актуально. Теперь если такое есть - это баг подписчика.

2019-02-28 11:08 UTC, Format-X22 commented on src/services/Registrator.js
> +    async _routeRealEventHandlers({ type, ...body }, blockNum) {
Если виртуальных больше нет - стоит убрать Real вообще.

2019-02-28 11:08 UTC, Format-X22 commented on src/services/Registrator.js
> +    _publishMapper(data) {
Имя метода звучит как-будто он что-то публикует. В идеале это конвертер/экстрактор.

2019-02-28 15:18 UTC, IvanBlacky commented
Closes #37

2019-02-28 17:11 UTC, bacher approved these changes

2019-03-12 11:13 UTC, Format-X22 requested changes

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Mention.js
> +                ...(await this.callService('prism', `prism.${type}`, {})),
Что-то весь метод состоит из вызовов внешних штук в ифах и внутри объектов, надо бы переписать с выносом в переменные отдельные, иначе как-то коряво выглядит всё.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Reply.js
> +            ...(await this.callService('prism', `prism.${type}`, {})),
Аналогично, надо бы поменять.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Repost.js
> +            ...(await this.callService('prism', `prism.${type}`, {})),
Аналогично.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Reward.js
> +            ...(await this.callService('prism', `prism.${type}`, {})),
Аналогично.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Subscribe.js
> +            ...(await this.callService('prism', `prism.${eventType}`, {})),
Аналогично.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Transfer.js
> +        const amount = rawAmount.shiftedBy(-rawAmount.sd() - quantity.decs - 1).toString();
Надо бы -rawAmount.sd() - quantity.decs - 1 вынести в отдельную переменную, имя которой пояснит а что тут происходит собственно, иначе загадочно выглядит.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Transfer.js
> +            ...(await this.callService('prism', `prism.${type}`, {})),
Аналогично про вложенные вызовы, что было в других файлах.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Vote.js
> +        const type = weight > 0 ? 'upvote' : 'downvote';
Тернарники зло, за исключением узких кейсов где нельзя адекватно без них.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/Vote.js
> +            ...(await this.callService('prism', `prism.${type}`, {})),
Аналогично про вложенные вызовы.

2019-03-12 11:13 UTC, Format-X22 commented on src/controllers/registrator/WitnessVote.js
> +            ...(await this.callService('prism', `prism.${eventType}`, {})),
Аналогично про вложенные вызовы.

2019-03-12 11:13 UTC, Format-X22 commented on src/models/Event.js
> +        comment: {
Надо бы сверху аннотацию написать почему и откуда такие поля, что они аж во всех эвентах то.

2019-03-12 11:13 UTC, Format-X22 commented on src/models/Event.js
> +                refBlockNum: Number,
Мелочь, но рефБлокНам обычно третьим.

2019-03-12 11:13 UTC, Format-X22 commented on src/models/Event.js
> +        schema: {
А оно точно работает?

2019-03-13 08:10 UTC, IvanBlacky commented
Closes #40

2019-03-18 16:42 UTC, IvanBlacky commented on src/models/Event.js
> +        schema: {
Точно :)

2019-03-18 16:44 UTC, IvanBlacky commented on src/controllers/registrator/Vote.js
> +            ...(await this.callService('prism', `prism.${type}`, {})),
Это был плейсхолдер пока не появится реальное API.

2019-05-14 14:46 UTC, bacher approved these changes

2019-05-14 14:47 UTC, IvanBlacky commented
Also closes #43 #40 #41 #42

2019-05-16 11:16 UTC, Format-X22 requested changes

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/connector/History.js
> +        if (types === 'all' || (Array.isArray(types) && types.includes('all'))) {
Если типы включают all и другое что-то - это баг клиента, надо кидать ошибку.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +        // if (user.includes('@')) {
Остался мусор.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +        // }
Остался мусор.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +            // нужно делать именно так, чтобы гарантировать порядок полей
Всё на английском у нас, кроме ядра, так повелось.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +            // нужно делать именно так, чтобы гарантировать порядок полей
Всё на английском у нас, кроме ядра, так повелось.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +            // нужно делать именно так, чтобы гарантировать порядок полей
Всё на английском у нас, кроме ядра, так повелось.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +    async callPrismService(
Вообще не говорящий метод, внутри происходит сильно другое и много бизнес-логики разной, надо переименовать, возможно порезать на подметоды, длинновато.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Reply.js
> +        { refBlockNum, author, permlink, parentPost, contractName },
Мегаметод прям, нужно резать.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Transfer.js
> +// const REWARD_ACTION_ACTOR = 'gls.publish';
Мусор остался?

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Transfer.js
> +                    console.info('Retrying');
Лишнее или логгер.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/Transfer.js
> +    async handle(
Мегаметод, надо резать.

2019-05-16 11:16 UTC, Format-X22 commented on src/controllers/registrator/WitnessVote.js
> +    async handle(
Есть что порезать и улучшить.

2019-05-16 11:16 UTC, Format-X22 commented on src/services/Registrator.js
> +                error = errJsonString === '{}' ? error : errJsonString;
Пропуск строки бы.

2019-05-16 11:16 UTC, Format-X22 commented on src/services/Registrator.js
> +            if (!transaction) {
Всё ещё актуально.

2019-05-16 11:16 UTC, Format-X22 commented on src/services/Registrator.js
> +        subscribe.on('block', data => {
Нужно изучить вопрос с очередностью - если допустимо что один блок ещё обрабатывается, а другой уже начал - тогда оставляем так, иначе - ядро до 3.23+ и eachBlock.

2019-05-24 10:43 UTC, bacher requested changes

2019-05-24 10:43 UTC, Bacher commented on src/controllers/connector/History.js
> +        for (let eventType of this._eachType(types)) {
const eventType

2019-05-24 10:43 UTC, Bacher commented on src/controllers/connector/History.js
> +        for (let id of ids) {
const id of ids

2019-05-24 10:43 UTC, Bacher commented on src/controllers/registrator/Abstract.js
> +        return await User.updateOne({ name }, { $set: { name } }, { upsert: true });
Зачем return если никто не пользуется результатом выполнения?

2019-05-24 10:43 UTC, Bacher commented on src/controllers/registrator/Mention.js
> +                return;
return без логирования ошибки?

2019-05-24 10:43 UTC, Bacher commented on src/controllers/registrator/Subscribe.js
> +            return;
return без логирования?

2019-05-24 10:43 UTC, Bacher commented on src/controllers/registrator/Transfer.js
> +                    return;
return без логирования ошибки?

2019-05-24 10:43 UTC, Bacher commented on src/controllers/registrator/Transfer.js
> +                return;
return без логирования ошибки?

2019-05-24 10:43 UTC, Bacher commented on src/controllers/registrator/Vote.js
> +            return;
return без логирования ошибки?

2019-05-24 10:43 UTC, Bacher commented on src/controllers/registrator/WitnessVote.js
> +                return;
return без логирования ошибки?

2019-05-24 10:43 UTC, Bacher commented on src/controllers/registrator/WitnessVote.js
> +        console.log(model.toObject());
Лишний console.log

2019-05-28 11:46 UTC, Format-X22 requested changes
Судя по всему ещё не все старые то исправлены.

2019-06-03 11:42 UTC, Format-X22 commented
Неадекватный пулреквест на 3 месяца со 100500 изменениями. Давайте больше НИКОГДА так не делать. Я его сейчас закрою и нужно будет сделать небольшими частями, по возможности. Если невозможно - пояснить почему.

2019-06-03 11:42 UTC, closed without merging