36 parse cyberway events
GolosChain/golos-notifications pull request #50
Opened 2019-06-14 14:06 UTC by IvanBlacky

2019-06-14 14:22 UTC, Format-X22 requested changes

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/connector/History.js
> +        if (!types.includes('all')) {
Нет, либо и так тоже, параметр может быть и массивом и строкой "all"

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/connector/History.js
> +        for (let eventType of this._eachType(types)) {
const

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/connector/History.js
> +        for (let id of ids) {
const и пропуск строки сверху.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +        if (postId) {
Все ифы можно в отдельный метод вынести вместе.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Abstract.js
> +    async callPrismService(
Что-то внутри оно делает больше чем просто вызывает, есть сомнения что имя метода говорит о том что происходит в реальности.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Mention.js
> +            user = await this.resolveName(user);
for (const user

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Mention.js
> +            let comment, actor, post;
У нас принято по строке на переменную.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Mention.js
> +        await this.waitForTransaction(transactionId);
Что-то сам метод гигантский вышел, нужно резать.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Reply.js
> +    async handle({ author, permlink, parentPost, contractName }, blockNum, transactionId) {
Очень большой метод с абстрактным названием, нужно резать.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Repost.js
> +    async handle({ author, permlink, rebloger, contractName }, blockNum, transactionId) {
Аналогично.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Reward.js
> +        { to: user, from, quantity, receiver, memo, contractName },
Аналогично. Само название то для входной точки ок, ведь по имени класса то понятно что именно там, но вот внутренние шаги - лапша.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/Reward.js
> +        let type;
Как на счет регулярки?

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/WitnessVote.js
> +                // from = await this.resolveName(from);
Забытый коммент.

2019-06-14 14:22 UTC, Format-X22 commented on src/controllers/registrator/WitnessVote.js
> +            } catch (error) {
Катч в катче так себе.

2019-06-14 14:22 UTC, Format-X22 commented on src/models/Event.js
> +                userId: String,
У нас принято типы объектом указывать с type всегда

2019-06-14 14:22 UTC, Format-X22 commented on src/services/Registrator.js
> +                    Logger.info(type);
Это точно не дебаг?

2019-06-14 14:24 UTC, IvanBlacky commented on src/controllers/connector/History.js
> +        if (!types.includes('all')) {
Если параметр -- строка `"all"`, то условие выполнится (т.к. `includes` работает и с массивом, и со строками)

2019-06-14 14:29 UTC, bacher requested changes

2019-06-14 14:29 UTC, Bacher commented on package.json
> +    "@types/node-rsa": "^1.0.0",
@types/node-rsa лишний имхо.

2019-06-14 14:29 UTC, Bacher commented on package.json
> +    "prettier": "^1.17.0"
Передвинуть devDependencies после dependencies

2019-06-14 14:29 UTC, Bacher commented on src/controllers/connector/History.js
> +        await Promise.all(markReadPromises);
Не лучше ли будет просто написать
```javascript
await Promise.all(ids.map(id => this._markReadWithUser(id, user));
```

лишние всякие массивы и push путают.

2019-06-14 14:29 UTC, Bacher commented on src/controllers/registrator/Abstract.js
> +const { JsonRpc } = require('cyberwayjs');
Этот импорт должен быть выше, до импортов по относительным путям.

2019-06-14 14:29 UTC, Bacher commented on src/controllers/registrator/Abstract.js
> +            Logger.error(`Error calling prism.waitForTransaction`, JSON.stringify(error, null, 2));
Лучше просто error

2019-06-14 14:29 UTC, Bacher commented on src/controllers/registrator/Reward.js
> +                from.includes('.publish') &&
Если .publish в конце строки то семантичнее будет использовать метод `.endsWith`

2019-06-14 14:29 UTC, Bacher commented on src/controllers/registrator/Transfer.js
> +        const currency = quantity[1];
Лучше в одну строку:

```javascript
const [amount, currency] = quantity.split(' ');
```

2019-06-14 14:29 UTC, Bacher commented on src/controllers/registrator/WitnessVote.js
> +                // from = await this.resolveName(from);
Забытый комментарий?

2019-06-14 14:37 UTC, IvanBlacky commented on src/controllers/registrator/Abstract.js
> +    async callPrismService(
Это просто формирование запроса в тот вид, который понимает призма

2019-06-14 14:38 UTC, IvanBlacky commented on src/controllers/registrator/Mention.js
> +            user = await this.resolveName(user);
оно меняется внутри, поэтому `let`

2019-06-14 14:38 UTC, IvanBlacky commented on src/controllers/registrator/Mention.js
> +            let comment, actor, post;
Prettier с этим не согласен :)

2019-06-14 15:19 UTC, IvanBlacky commented on src/services/Registrator.js
> +                    Logger.info(type);
Очень полезно иметь в логах для поиска ошибок, предлагаю и в продакшене оставить

2019-06-14 15:35 UTC, IvanBlacky commented on src/controllers/registrator/Reward.js
> +        let type;
Можно это в тикет вынести -- регулярка не самая простая выходит

2019-06-14 15:59 UTC, bacher requested changes

2019-06-14 15:59 UTC, Bacher commented on src/controllers/registrator/Mention.js
> +            user = await this.resolveName(user);
Некорректно назван `for (let user`, если это username, то лучше так и назвать, и будет const.

`for (const username of users)`

2019-06-14 15:59 UTC, Bacher commented on src/controllers/registrator/Mention.js
> +            user = await this.resolveName(user);
Вообще использовать одну и туже переменную для разных типов данных плохой подход.

2019-06-14 16:12 UTC, bacher approved these changes

2019-06-17 11:17 UTC, Format-X22 commented on src/services/Registrator.js
> +                    Logger.info(type);
Не, такое закидывание консоли - излишнее. Возможно когда сделаем вариативность лога - будет смысл в дев-режиме.

2019-06-17 11:17 UTC, Format-X22 requested changes
Всё ещё есть некоторые недоработки.

2019-06-17 11:39 UTC, Format-X22 approved these changes

2019-06-17 11:39 UTC, merged